version: '3.8'

services:
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: 'listen --api-key "${STRIPE_API_KEY}" --device-name "${STRIPE_DEVICE_NAME}" --forward-to host.docker.internal:3000/api/stripe/webhook'
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
